# Generated by Django 4.2.11 on 2024-05-02 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PurchaseOrder',
        ),
    ]
